use_default_settings:
  engines:
    keep_only:
      - bing

server:
  secret_key: "53a412c00dd84b00cb0318f1e0de330c" 
  limiter: false

search:
  autocomplete: ""
  formats:
    - html
    - json

engines:
  - name: bing
    engine: bing
    shortcut: bi
    disabled: false