use_default_settings: true 
server: 
  secret_key: "dfeabb8d9df26211cd51b97d7310fa8a963507f40c37e57d06dbd2ea4ad6f80c" 
  limiter: false 
search: 
  formats: 
    - html 
    - json
engines:
  - name: google
    engine: google
    shortcut: go
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

    # test auto deployment