use_default_settings:
  engines:
    keep_only:
      - duckduckgo
      - wikipedia
      - wikidata

server:
  secret_key: "53a412c00dd84b00cb0318f1e0de330c" 
  limiter: false

search:
  formats:
    - html
    - json

engines:
  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

  - name: wikipedia
    engine: wikipedia
    shortcut: wp

  - name: wikidata
    engine: wikidata
    shortcut: wd